spring:
  application:
    name: Order Drink API Gateway
  #Default, override for environment
  profiles:
    active: local
logging:
  level:
    root: INFO
management:
  endpoints:
    enabled-by-default: true
graph:
  ql:
    resource: graphql
bartender:
  api:
    base:
      #Environment override required
      uri:
    graph:
      ql:
        url: ${bartender.api.base.uri}${graph.ql.resource}
server:
  port: 8082